
export class SamlConfigurationObject{
    path : string;
    entryPoint : string;
    issuer : string;
    callbackUrl : string;
    /**
     * privateCert is autogenerated from privateCertLocation
     */
    privateCert : string;
    cert : string;
}